# Generated by Django 3.0.2 on 2020-03-08 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40, verbose_name='provider name')),
                ('token_type', models.CharField(blank=True, max_length=40, verbose_name='token type')),
                ('access_token', models.CharField(max_length=200, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, max_length=200, verbose_name='refresh token')),
                ('expires_at', models.PositiveIntegerField(verbose_name='expiration date in seconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', related_query_name='token', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'oauth2 token',
                'verbose_name_plural': 'oauth2 tokens',
            },
        ),
    ]
