# Generated by Django 3.0.2 on 2020-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
