# Generated by Django 3.0.2 on 2020-03-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_oauth2token'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='login',
            field=models.CharField(default='admin', max_length=150, verbose_name='login'),
            preserve_default=False,
        ),
    ]
