# Generated by Django 3.0.3 on 2020-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'Gitlab')], max_length=40, verbose_name='provider name'),
        ),
    ]
