# Generated by Django 3.0.3 on 2020-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200425_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='refresh token'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='token_type',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='token type'),
        ),
    ]
