# Generated by Django 3.0.2 on 2020-03-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitHubUserAccount',
        ),
    ]
