# Generated by Django 3.0.2 on 2020-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_oauth2token_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='remote_id',
            field=models.IntegerField(default=1, verbose_name='user id from provider site'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='oauth2token',
            constraint=models.UniqueConstraint(fields=('provider', 'remote_id'), name='unique_oauth'),
        ),
    ]
