# Generated by Django 3.0.2 on 2020-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200308_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='expires_at',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='expiration date in seconds'),
        ),
    ]
