from copy import deepcopy
from typing import Union
from unittest import mock

import pytest
from django.utils import timezone


@pytest.fixture()
def create_mock_response():
    def _create_mock_response(data: Union[list, dict] = None, status_code: int = 200, **kwargs) -> mock.MagicMock:
        return mock.MagicMock(json=mock.MagicMock(return_value=deepcopy(data)), status_code=status_code, **kwargs)

    return _create_mock_response


@pytest.fixture()
def github_token_json() -> dict:
    return {
        "access_token": "e72e16c7e42f292c6912e7710c838347ae178b4a",
        "scope": "repo,gist",
        "token_type": "bearer",
    }


@pytest.fixture()
def github_user_json() -> dict:
    return {
        "login": "stefanitsky",
        "id": 22547214,
        "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
        "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stefanitsky",
        "html_url": "https://github.com/stefanitsky",
        "followers_url": "https://api.github.com/users/stefanitsky/followers",
        "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
        "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
        "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
        "repos_url": "https://api.github.com/users/stefanitsky/repos",
        "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
        "type": "User",
        "site_admin": False,
        "name": "Alexandr Stefanitsky-Mozdor",
        "company": None,
        "blog": "",
        "location": "Russian Federation",
        "email": "stefanitsky.mozdor@gmail.com",
        "hireable": None,
        "bio": None,
        "twitter_username": None,
        "public_repos": 11,
        "public_gists": 1,
        "followers": 0,
        "following": 0,
        "created_at": "2016-09-30T15:43:07Z",
        "updated_at": "2020-07-24T14:57:55Z",
    }


@pytest.fixture()
def github_user_repositories_json() -> list:
    return [
        {
            "id": 242516030,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNDI1MTYwMzA=",
            "name": "openwiden-frontend",
            "full_name": "OpenWiden/openwiden-frontend",
            "private": False,
            "owner": {
                "login": "OpenWiden",
                "id": 59751674,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5NzUxNjc0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/59751674?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/OpenWiden",
                "html_url": "https://github.com/OpenWiden",
                "followers_url": "https://api.github.com/users/OpenWiden/followers",
                "following_url": "https://api.github.com/users/OpenWiden/following{/other_user}",
                "gists_url": "https://api.github.com/users/OpenWiden/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/OpenWiden/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/OpenWiden/subscriptions",
                "organizations_url": "https://api.github.com/users/OpenWiden/orgs",
                "repos_url": "https://api.github.com/users/OpenWiden/repos",
                "events_url": "https://api.github.com/users/OpenWiden/events{/privacy}",
                "received_events_url": "https://api.github.com/users/OpenWiden/received_events",
                "type": "Organization",
                "site_admin": False,
            },
            "html_url": "https://github.com/OpenWiden/openwiden-frontend",
            "description": "OpenWiden - open source aggregator platform with a list of open source projects that helps developers find a great project and contribute to it.",  # noqa: E501
            "fork": False,
            "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend",
            "forks_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/forks",
            "keys_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/collaborators{/collaborator}",  # noqa: E501
            "teams_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/teams",
            "hooks_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/hooks",
            "issue_events_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/events{/number}",
            "events_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/events",
            "assignees_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/assignees{/user}",
            "branches_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/branches{/branch}",
            "tags_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/tags",
            "blobs_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/languages",
            "stargazers_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/stargazers",
            "contributors_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/contributors",
            "subscribers_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/subscribers",
            "subscription_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/subscription",
            "commits_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/contents/{+path}",
            "compare_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/merges",
            "archive_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/downloads",
            "issues_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues{/number}",
            "pulls_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/notifications{?since,all,participating}",  # noqa: E501
            "labels_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/labels{/name}",
            "releases_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/releases{/id}",
            "deployments_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/deployments",
            "created_at": "2020-02-23T12:50:01Z",
            "updated_at": "2020-06-26T15:13:53Z",
            "pushed_at": "2020-06-26T15:13:55Z",
            "git_url": "git://github.com/OpenWiden/openwiden-frontend.git",
            "ssh_url": "git@github.com:OpenWiden/openwiden-frontend.git",
            "clone_url": "https://github.com/OpenWiden/openwiden-frontend.git",
            "svn_url": "https://github.com/OpenWiden/openwiden-frontend",
            "homepage": "https://openwiden.com/",
            "size": 854,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "Vue",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 0,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 6,
            "license": None,
            "forks": 0,
            "open_issues": 6,
            "watchers": 0,
            "default_branch": "develop",
            "permissions": {"admin": True, "push": True, "pull": True},
        },
        {
            "id": 250661059,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
            "name": "yandex_market_language",
            "full_name": "stefanitsky/yandex_market_language",
            "private": False,
            "owner": {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False,
            },
            "html_url": "https://github.com/stefanitsky/yandex_market_language",
            "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",  # noqa: E501
            "fork": False,
            "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
            "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
            "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",  # noqa: E501
            "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
            "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
            "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",  # noqa: E501
            "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
            "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
            "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
            "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
            "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
            "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
            "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
            "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
            "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
            "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",  # noqa: E501
            "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
            "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
            "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
            "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
            "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",  # noqa: E501
            "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
            "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
            "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
            "created_at": "2020-03-27T22:21:23Z",
            "updated_at": "2020-07-26T10:15:15Z",
            "pushed_at": "2020-07-26T10:15:13Z",
            "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
            "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
            "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
            "svn_url": "https://github.com/stefanitsky/yandex_market_language",
            "homepage": None,
            "size": 192,
            "stargazers_count": 3,
            "watchers_count": 3,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 2,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 2,
            "license": {
                "key": "other",
                "name": "Other",
                "spdx_id": "NOASSERTION",
                "url": None,
                "node_id": "MDc6TGljZW5zZTA=",
            },
            "forks": 2,
            "open_issues": 2,
            "watchers": 3,
            "default_branch": "master",
            "permissions": {"admin": True, "push": True, "pull": True},
        },
    ]


@pytest.fixture()
def github_repository_json() -> dict:
    return {
        "id": 243082080,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNDMwODIwODA=",
        "name": "openwiden-backend",
        "full_name": "OpenWiden/openwiden-backend",
        "private": False,
        "owner": {
            "login": "OpenWiden",
            "id": 59751674,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5NzUxNjc0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/59751674?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/OpenWiden",
            "html_url": "https://github.com/OpenWiden",
            "followers_url": "https://api.github.com/users/OpenWiden/followers",
            "following_url": "https://api.github.com/users/OpenWiden/following{/other_user}",
            "gists_url": "https://api.github.com/users/OpenWiden/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/OpenWiden/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/OpenWiden/subscriptions",
            "organizations_url": "https://api.github.com/users/OpenWiden/orgs",
            "repos_url": "https://api.github.com/users/OpenWiden/repos",
            "events_url": "https://api.github.com/users/OpenWiden/events{/privacy}",
            "received_events_url": "https://api.github.com/users/OpenWiden/received_events",
            "type": "Organization",
            "site_admin": False,
        },
        "html_url": "https://github.com/OpenWiden/openwiden-backend",
        "description": "OpenWiden - An Open Source Project Search Platform.",
        "fork": False,
        "url": "https://api.github.com/repos/OpenWiden/openwiden-backend",
        "forks_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/forks",
        "keys_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/teams",
        "hooks_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/hooks",
        "issue_events_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/issues/events{/number}",
        "events_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/events",
        "assignees_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/assignees{/user}",
        "branches_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/branches{/branch}",
        "tags_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/tags",
        "blobs_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/languages",
        "stargazers_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/stargazers",
        "contributors_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/contributors",
        "subscribers_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/subscribers",
        "subscription_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/subscription",
        "commits_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/contents/{+path}",
        "compare_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/merges",
        "archive_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/downloads",
        "issues_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/issues{/number}",
        "pulls_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/notifications{?since,all,participating}",  # noqa: E501
        "labels_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/labels{/name}",
        "releases_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/releases{/id}",
        "deployments_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/deployments",
        "created_at": "2020-02-25T19:17:21Z",
        "updated_at": "2020-05-03T17:34:17Z",
        "pushed_at": "2020-07-26T14:19:05Z",
        "git_url": "git://github.com/OpenWiden/openwiden-backend.git",
        "ssh_url": "git@github.com:OpenWiden/openwiden-backend.git",
        "clone_url": "https://github.com/OpenWiden/openwiden-backend.git",
        "svn_url": "https://github.com/OpenWiden/openwiden-backend",
        "homepage": None,
        "size": 1881,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 0,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 1,
        "license": {
            "key": "gpl-3.0",
            "name": "GNU General Public License v3.0",
            "spdx_id": "GPL-3.0",
            "url": "https://api.github.com/licenses/gpl-3.0",
            "node_id": "MDc6TGljZW5zZTk=",
        },
        "forks": 0,
        "open_issues": 1,
        "watchers": 1,
        "default_branch": "master",
        "permissions": {"admin": True, "push": True, "pull": True},
        "temp_clone_token": "",
        "organization": {
            "login": "OpenWiden",
            "id": 59751674,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5NzUxNjc0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/59751674?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/OpenWiden",
            "html_url": "https://github.com/OpenWiden",
            "followers_url": "https://api.github.com/users/OpenWiden/followers",
            "following_url": "https://api.github.com/users/OpenWiden/following{/other_user}",
            "gists_url": "https://api.github.com/users/OpenWiden/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/OpenWiden/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/OpenWiden/subscriptions",
            "organizations_url": "https://api.github.com/users/OpenWiden/orgs",
            "repos_url": "https://api.github.com/users/OpenWiden/repos",
            "events_url": "https://api.github.com/users/OpenWiden/events{/privacy}",
            "received_events_url": "https://api.github.com/users/OpenWiden/received_events",
            "type": "Organization",
            "site_admin": False,
        },
        "network_count": 0,
        "subscribers_count": 1,
    }


@pytest.fixture()
def github_repository_languages_json() -> dict:
    return {
        "Python": 105410,
        "Makefile": 1593,
        "Dockerfile": 334,
        "Shell": 103,
    }


@pytest.fixture()
def github_repository_issues_json() -> list:
    return [
        {
            "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/28",
            "repository_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend",
            "labels_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/28/labels{/name}",
            "comments_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/28/comments",
            "events_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/28/events",
            "html_url": "https://github.com/OpenWiden/openwiden-frontend/issues/28",
            "id": 627475254,
            "node_id": "MDU6SXNzdWU2Mjc0NzUyNTQ=",
            "number": 28,
            "title": "test #1",
            "user": {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False,
            },
            "labels": [
                {
                    "id": 1865631985,
                    "node_id": "MDU6TGFiZWwxODY1NjMxOTg1",
                    "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/labels/bug",
                    "name": "bug",
                    "color": "d73a4a",
                    "default": True,
                    "description": "Something isn't working",
                }
            ],
            "state": "open",
            "locked": False,
            "assignee": None,
            "assignees": [],
            "milestone": None,
            "comments": 0,
            "created_at": "2020-05-29T19:03:06Z",
            "updated_at": "2020-07-12T12:39:34Z",
            "closed_at": None,
            "author_association": "MEMBER",
            "active_lock_reason": None,
            "body": "",
            "performed_via_github_app": None,
        },
        {
            "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/29",
            "repository_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend",
            "labels_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/29/labels{/name}",
            "comments_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/29/comments",
            "events_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/29/events",
            "html_url": "https://github.com/OpenWiden/openwiden-frontend/issues/29",
            "id": 627475255,
            "node_id": "MDU6SXNzdWU2Mjc0NzUyNTA=",
            "number": 29,
            "title": "test #2",
            "user": {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False,
            },
            "labels": [
                {
                    "id": 1865631985,
                    "node_id": "MDU6TGFiZWwxODY1NjMxOTg1",
                    "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/labels/bug",
                    "name": "bug",
                    "color": "d73a4a",
                    "default": True,
                    "description": "Something isn't working",
                }
            ],
            "state": "open",
            "locked": False,
            "assignee": None,
            "assignees": [],
            "milestone": None,
            "comments": 0,
            "created_at": "2020-06-29T19:03:06Z",
            "updated_at": "2020-07-12T12:39:34Z",
            "closed_at": None,
            "author_association": "MEMBER",
            "active_lock_reason": None,
            "body": "",
            "performed_via_github_app": None,
        },
        {
            "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/26",
            "repository_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend",
            "labels_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/26/labels{/name}",
            "comments_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/26/comments",
            "events_url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/issues/26/events",
            "html_url": "https://github.com/OpenWiden/openwiden-frontend/pull/26",
            "id": 627346510,
            "node_id": "MDExOlB1bGxSZXF1ZXN0NDI1MTY3ODAy",
            "number": 26,
            "title": "WIP: Add mobile header with sidebar menu",
            "user": {
                "login": "NooNoo1337",
                "id": 30805588,
                "node_id": "MDQ6VXNlcjMwODA1NTg4",
                "avatar_url": "https://avatars3.githubusercontent.com/u/30805588?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/NooNoo1337",
                "html_url": "https://github.com/NooNoo1337",
                "followers_url": "https://api.github.com/users/NooNoo1337/followers",
                "following_url": "https://api.github.com/users/NooNoo1337/following{/other_user}",
                "gists_url": "https://api.github.com/users/NooNoo1337/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/NooNoo1337/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/NooNoo1337/subscriptions",
                "organizations_url": "https://api.github.com/users/NooNoo1337/orgs",
                "repos_url": "https://api.github.com/users/NooNoo1337/repos",
                "events_url": "https://api.github.com/users/NooNoo1337/events{/privacy}",
                "received_events_url": "https://api.github.com/users/NooNoo1337/received_events",
                "type": "User",
                "site_admin": False,
            },
            "labels": [],
            "state": "open",
            "locked": False,
            "assignee": None,
            "assignees": [],
            "milestone": None,
            "comments": 0,
            "created_at": "2020-05-29T15:20:24Z",
            "updated_at": "2020-05-29T15:20:24Z",
            "closed_at": None,
            "author_association": "MEMBER",
            "active_lock_reason": None,
            "pull_request": {
                "url": "https://api.github.com/repos/OpenWiden/openwiden-frontend/pulls/26",
                "html_url": "https://github.com/OpenWiden/openwiden-frontend/pull/26",
                "diff_url": "https://github.com/OpenWiden/openwiden-frontend/pull/26.diff",
                "patch_url": "https://github.com/OpenWiden/openwiden-frontend/pull/26.patch",
            },
            "body": "",
            "performed_via_github_app": None,
        },
    ]


@pytest.fixture()
def github_webhook_create_json() -> dict:
    return {
        "type": "Repository",
        "id": 237402988,
        "name": "web",
        "active": True,
        "events": ["issues", "repository"],
        "config": {
            "content_type": "json",
            "insecure_ssl": "0",
            "secret": "********",
            "url": "https://openwiden.com/api/v1/webhooks/github/1/receive/",
        },
        "updated_at": "2020-07-28T13:41:37Z",
        "created_at": "2020-07-28T13:41:37Z",
        "url": "https://api.github.com/repos/OpenWiden/openwiden-backend/hooks/237402988",
        "test_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/hooks/237402988/test",
        "ping_url": "https://api.github.com/repos/OpenWiden/openwiden-backend/hooks/237402988/pings",
        "last_response": {"code": None, "status": "unused", "message": None},
    }


@pytest.fixture()
def github_organization_json() -> dict:
    return {
        "login": "OpenWiden",
        "id": 59751674,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5NzUxNjc0",
        "url": "https://api.github.com/orgs/OpenWiden",
        "repos_url": "https://api.github.com/orgs/OpenWiden/repos",
        "events_url": "https://api.github.com/orgs/OpenWiden/events",
        "hooks_url": "https://api.github.com/orgs/OpenWiden/hooks",
        "issues_url": "https://api.github.com/orgs/OpenWiden/issues",
        "members_url": "https://api.github.com/orgs/OpenWiden/members{/member}",
        "public_members_url": "https://api.github.com/orgs/OpenWiden/public_members{/member}",
        "avatar_url": "https://avatars3.githubusercontent.com/u/59751674?v=4",
        "description": None,
        "name": None,
        "company": None,
        "blog": None,
        "location": None,
        "email": None,
        "twitter_username": None,
        "is_verified": False,
        "has_organization_projects": True,
        "has_repository_projects": True,
        "public_repos": 5,
        "public_gists": 0,
        "followers": 0,
        "following": 0,
        "html_url": "https://github.com/OpenWiden",
        "created_at": "2020-01-10T23:56:58Z",
        "updated_at": "2020-04-13T10:19:45Z",
        "type": "Organization",
        "total_private_repos": 0,
        "owned_private_repos": 0,
        "private_gists": None,
        "disk_usage": None,
        "collaborators": None,
        "billing_email": None,
        "default_repository_permission": None,
        "members_can_create_repositories": True,
        "two_factor_requirement_enabled": None,
        "plan": {"name": "free", "space": 976562499, "private_repos": 10000, "filled_seats": 3, "seats": 1},
    }


@pytest.fixture()
def github_user_membership_for_organization_json() -> dict:
    return {
        "url": "https://api.github.com/orgs/OpenWiden/memberships/stefanitsky",
        "state": "active",
        "role": "admin",
        "organization_url": "https://api.github.com/orgs/OpenWiden",
        "user": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False,
        },
        "organization": {
            "login": "OpenWiden",
            "id": 59751674,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5NzUxNjc0",
            "url": "https://api.github.com/orgs/OpenWiden",
            "repos_url": "https://api.github.com/orgs/OpenWiden/repos",
            "events_url": "https://api.github.com/orgs/OpenWiden/events",
            "hooks_url": "https://api.github.com/orgs/OpenWiden/hooks",
            "issues_url": "https://api.github.com/orgs/OpenWiden/issues",
            "members_url": "https://api.github.com/orgs/OpenWiden/members{/member}",
            "public_members_url": "https://api.github.com/orgs/OpenWiden/public_members{/member}",
            "avatar_url": "https://avatars3.githubusercontent.com/u/59751674?v=4",
            "description": None,
        },
    }


@pytest.fixture()
def gitlab_token_json() -> dict:
    return {
        "access_token": "de6780bc506a0446309bd9362820ba8aed28aa506c71eedbe1c5c4f9dd350e54",
        "token_type": "bearer",
        "refresh_token": "8257e65c97202ed1726cf9571600918f3bffb2544b26e00a61df9897668c33a1",
        "scope": "api",
        "created_at": timezone.now().timestamp(),
    }


@pytest.fixture()
def gitlab_user_json() -> dict:
    return {
        "id": 927868,
        "name": "stefanitsky",
        "username": "stefanitsky",
        "state": "active",
        "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
        "web_url": "https://gitlab.com/stefanitsky",
        "created_at": "2017-01-05T18:01:01.934Z",
        "bio": "",
        "bio_html": "",
        "location": "",
        "public_email": "stefanitsky.mozdor@gmail.com",
        "skype": "",
        "linkedin": "",
        "twitter": "",
        "website_url": "",
        "organization": "",
        "job_title": "",
        "work_information": None,
        "last_sign_in_at": "2020-07-21T08:39:20.843Z",
        "confirmed_at": "2017-01-05T18:01:01.497Z",
        "last_activity_on": "2020-07-28",
        "email": "stefanitsky.mozdor@gmail.com",
        "theme_id": 2,
        "color_scheme_id": 2,
        "projects_limit": 100000,
        "current_sign_in_at": "2020-07-27T12:31:22.522Z",
        "identities": [
            {"provider": "google_oauth2", "extern_uid": "117180852700601501631", "saml_provider_id": None,},
            {"provider": "github", "extern_uid": "22547214", "saml_provider_id": None,},
        ],
        "can_create_group": True,
        "can_create_project": True,
        "two_factor_enabled": False,
        "external": False,
        "private_profile": False,
        "shared_runners_minutes_limit": 2000,
        "extra_shared_runners_minutes_limit": None,
    }


@pytest.fixture()
def gitlab_user_repositories_json() -> list:
    return [
        {
            "id": 18579683,
            "description": "Example plain HTML site using GitLab Pages: https://pages.gitlab.io/plain-html",
            "name": "Test group repository",
            "name_with_namespace": "OpenWiden / Test group repository",
            "path": "test-group-repository",
            "path_with_namespace": "openwiden/test-group-repository",
            "created_at": "2020-05-04T21:07:06.734Z",
            "default_branch": "master",
            "tag_list": [],
            "ssh_url_to_repo": "git@gitlab.com:openwiden/test-group-repository.git",
            "http_url_to_repo": "https://gitlab.com/openwiden/test-group-repository.git",
            "web_url": "https://gitlab.com/openwiden/test-group-repository",
            "readme_url": "https://gitlab.com/openwiden/test-group-repository/-/blob/master/README.md",
            "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/project/avatar/18579683/HTML5_Logo_512.png",  # noqa: E501
            "forks_count": 0,
            "star_count": 0,
            "last_activity_at": "2020-05-10T11:42:58.171Z",
            "namespace": {
                "id": 7468920,
                "name": "OpenWiden",
                "path": "openwiden",
                "kind": "group",
                "full_path": "openwiden",
                "parent_id": None,
                "avatar_url": None,
                "web_url": "https://gitlab.com/groups/openwiden",
            },
            "_links": {
                "self": "https://gitlab.com/api/v4/projects/18579683",
                "issues": "https://gitlab.com/api/v4/projects/18579683/issues",
                "merge_requests": "https://gitlab.com/api/v4/projects/18579683/merge_requests",
                "repo_branches": "https://gitlab.com/api/v4/projects/18579683/repository/branches",
                "labels": "https://gitlab.com/api/v4/projects/18579683/labels",
                "events": "https://gitlab.com/api/v4/projects/18579683/events",
                "members": "https://gitlab.com/api/v4/projects/18579683/members",
            },
            "packages_enabled": True,
            "empty_repo": False,
            "archived": False,
            "visibility": "public",
            "resolve_outdated_diff_discussions": None,
            "container_registry_enabled": False,
            "container_expiration_policy": {
                "cadence": "7d",
                "enabled": True,
                "keep_n": None,
                "older_than": None,
                "name_regex": None,
                "name_regex_keep": None,
                "next_run_at": "2020-08-04T07:53:34.107Z",
            },
            "issues_enabled": True,
            "merge_requests_enabled": True,
            "wiki_enabled": False,
            "jobs_enabled": True,
            "snippets_enabled": False,
            "service_desk_enabled": None,
            "service_desk_address": None,
            "can_create_merge_request_in": True,
            "issues_access_level": "enabled",
            "repository_access_level": "enabled",
            "merge_requests_access_level": "enabled",
            "forking_access_level": "enabled",
            "wiki_access_level": "disabled",
            "builds_access_level": "enabled",
            "snippets_access_level": "disabled",
            "pages_access_level": "public",
            "emails_disabled": False,
            "shared_runners_enabled": True,
            "lfs_enabled": True,
            "creator_id": 927868,
            "import_status": "finished",
            "open_issues_count": 1,
            "ci_default_git_depth": 50,
            "public_jobs": True,
            "build_timeout": 3600,
            "auto_cancel_pending_pipelines": "enabled",
            "build_coverage_regex": "",
            "ci_config_path": None,
            "shared_with_groups": [],
            "only_allow_merge_if_pipeline_succeeds": False,
            "allow_merge_on_skipped_pipeline": None,
            "request_access_enabled": False,
            "only_allow_merge_if_all_discussions_are_resolved": False,
            "remove_source_branch_after_merge": True,
            "printing_merge_request_link_enabled": True,
            "merge_method": "merge",
            "suggestion_commit_message": None,
            "auto_devops_enabled": False,
            "auto_devops_deploy_strategy": "continuous",
            "autoclose_referenced_issues": True,
            "approvals_before_merge": 0,
            "mirror": False,
            "external_authorization_classification_label": "",
            "marked_for_deletion_at": None,
            "marked_for_deletion_on": None,
            "compliance_frameworks": [],
            "permissions": {
                "project_access": {"access_level": 40, "notification_level": None},
                "group_access": {"access_level": 50, "notification_level": 3},
            },
        },
        {
            "id": 18579655,
            "description": "",
            "name": "Test",
            "name_with_namespace": "stefanitsky / Test",
            "path": "test",
            "path_with_namespace": "stefanitsky/test",
            "created_at": "2020-05-04T21:04:30.365Z",
            "default_branch": "master",
            "tag_list": [],
            "ssh_url_to_repo": "git@gitlab.com:stefanitsky/test.git",
            "http_url_to_repo": "https://gitlab.com/stefanitsky/test.git",
            "web_url": "https://gitlab.com/stefanitsky/test",
            "readme_url": "https://gitlab.com/stefanitsky/test/-/blob/master/README.md",
            "avatar_url": None,
            "forks_count": 0,
            "star_count": 0,
            "last_activity_at": "2020-05-04T21:04:30.365Z",
            "namespace": {
                "id": 1114296,
                "name": "stefanitsky",
                "path": "stefanitsky",
                "kind": "user",
                "full_path": "stefanitsky",
                "parent_id": None,
                "avatar_url": "/uploads/-/system/user/avatar/927868/avatar.png",
                "web_url": "https://gitlab.com/stefanitsky",
            },
            "_links": {
                "self": "https://gitlab.com/api/v4/projects/18579655",
                "issues": "https://gitlab.com/api/v4/projects/18579655/issues",
                "merge_requests": "https://gitlab.com/api/v4/projects/18579655/merge_requests",
                "repo_branches": "https://gitlab.com/api/v4/projects/18579655/repository/branches",
                "labels": "https://gitlab.com/api/v4/projects/18579655/labels",
                "events": "https://gitlab.com/api/v4/projects/18579655/events",
                "members": "https://gitlab.com/api/v4/projects/18579655/members",
            },
            "packages_enabled": True,
            "empty_repo": False,
            "archived": False,
            "visibility": "public",
            "owner": {
                "id": 927868,
                "name": "stefanitsky",
                "username": "stefanitsky",
                "state": "active",
                "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
                "web_url": "https://gitlab.com/stefanitsky",
            },
            "resolve_outdated_diff_discussions": False,
            "container_registry_enabled": True,
            "container_expiration_policy": {
                "cadence": "7d",
                "enabled": True,
                "keep_n": None,
                "older_than": None,
                "name_regex": None,
                "name_regex_keep": None,
                "next_run_at": "2020-08-04T07:53:33.412Z",
            },
            "issues_enabled": True,
            "merge_requests_enabled": True,
            "wiki_enabled": True,
            "jobs_enabled": True,
            "snippets_enabled": True,
            "service_desk_enabled": True,
            "service_desk_address": "incoming+stefanitsky-test-18579655-issue-@incoming.gitlab.com",
            "can_create_merge_request_in": True,
            "issues_access_level": "enabled",
            "repository_access_level": "enabled",
            "merge_requests_access_level": "enabled",
            "forking_access_level": "enabled",
            "wiki_access_level": "enabled",
            "builds_access_level": "enabled",
            "snippets_access_level": "enabled",
            "pages_access_level": "enabled",
            "emails_disabled": None,
            "shared_runners_enabled": True,
            "lfs_enabled": True,
            "creator_id": 927868,
            "import_status": "none",
            "open_issues_count": 0,
            "ci_default_git_depth": 50,
            "public_jobs": True,
            "build_timeout": 3600,
            "auto_cancel_pending_pipelines": "enabled",
            "build_coverage_regex": None,
            "ci_config_path": None,
            "shared_with_groups": [],
            "only_allow_merge_if_pipeline_succeeds": False,
            "allow_merge_on_skipped_pipeline": None,
            "request_access_enabled": True,
            "only_allow_merge_if_all_discussions_are_resolved": False,
            "remove_source_branch_after_merge": True,
            "printing_merge_request_link_enabled": True,
            "merge_method": "merge",
            "suggestion_commit_message": None,
            "auto_devops_enabled": False,
            "auto_devops_deploy_strategy": "continuous",
            "autoclose_referenced_issues": True,
            "approvals_before_merge": 0,
            "mirror": False,
            "external_authorization_classification_label": "",
            "marked_for_deletion_at": None,
            "marked_for_deletion_on": None,
            "compliance_frameworks": [],
            "permissions": {"project_access": {"access_level": 40, "notification_level": 3}, "group_access": None},
        },
    ]


@pytest.fixture()
def gitlab_repository_json() -> dict:
    return {
        "id": 18579664,
        "description": None,
        "name": "Test2",
        "name_with_namespace": "stefanitsky / Test2",
        "path": "test2",
        "path_with_namespace": "stefanitsky/test2",
        "created_at": "2020-05-04T21:05:24.121Z",
        "default_branch": "master",
        "tag_list": [],
        "ssh_url_to_repo": "git@gitlab.com:stefanitsky/test2.git",
        "http_url_to_repo": "https://gitlab.com/stefanitsky/test2.git",
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "readme_url": "https://gitlab.com/stefanitsky/test2/-/blob/master/README.md",
        "avatar_url": None,
        "forks_count": 0,
        "star_count": 0,
        "last_activity_at": "2020-07-19T18:54:44.363Z",
        "namespace": {
            "id": 1114296,
            "name": "stefanitsky",
            "path": "stefanitsky",
            "kind": "user",
            "full_path": "stefanitsky",
            "parent_id": None,
            "avatar_url": "/uploads/-/system/user/avatar/927868/avatar.png",
            "web_url": "https://gitlab.com/stefanitsky",
        },
        "_links": {
            "self": "https://gitlab.com/api/v4/projects/18579664",
            "issues": "https://gitlab.com/api/v4/projects/18579664/issues",
            "merge_requests": "https://gitlab.com/api/v4/projects/18579664/merge_requests",
            "repo_branches": "https://gitlab.com/api/v4/projects/18579664/repository/branches",
            "labels": "https://gitlab.com/api/v4/projects/18579664/labels",
            "events": "https://gitlab.com/api/v4/projects/18579664/events",
            "members": "https://gitlab.com/api/v4/projects/18579664/members",
        },
        "packages_enabled": True,
        "empty_repo": False,
        "archived": False,
        "visibility": "public",
        "owner": {
            "id": 927868,
            "name": "stefanitsky",
            "username": "stefanitsky",
            "state": "active",
            "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
            "web_url": "https://gitlab.com/stefanitsky",
        },
        "resolve_outdated_diff_discussions": False,
        "container_registry_enabled": True,
        "container_expiration_policy": {
            "cadence": "7d",
            "enabled": True,
            "keep_n": None,
            "older_than": None,
            "name_regex": None,
            "name_regex_keep": None,
            "next_run_at": "2020-08-04T07:53:33.638Z",
        },
        "issues_enabled": True,
        "merge_requests_enabled": True,
        "wiki_enabled": True,
        "jobs_enabled": True,
        "snippets_enabled": True,
        "service_desk_enabled": True,
        "service_desk_address": "incoming+stefanitsky-test2-18579664-issue-@incoming.gitlab.com",
        "can_create_merge_request_in": True,
        "issues_access_level": "enabled",
        "repository_access_level": "enabled",
        "merge_requests_access_level": "enabled",
        "forking_access_level": "enabled",
        "wiki_access_level": "enabled",
        "builds_access_level": "enabled",
        "snippets_access_level": "enabled",
        "pages_access_level": "enabled",
        "emails_disabled": None,
        "shared_runners_enabled": True,
        "lfs_enabled": True,
        "creator_id": 927868,
        "import_status": "finished",
        "import_error": None,
        "open_issues_count": 2,
        "runners_token": "LpvDEbhwzFbBftsrksMQ",
        "ci_default_git_depth": 50,
        "public_jobs": True,
        "build_git_strategy": "fetch",
        "build_timeout": 3600,
        "auto_cancel_pending_pipelines": "enabled",
        "build_coverage_regex": None,
        "ci_config_path": None,
        "shared_with_groups": [],
        "only_allow_merge_if_pipeline_succeeds": False,
        "allow_merge_on_skipped_pipeline": None,
        "request_access_enabled": False,
        "only_allow_merge_if_all_discussions_are_resolved": False,
        "remove_source_branch_after_merge": True,
        "printing_merge_request_link_enabled": True,
        "merge_method": "merge",
        "suggestion_commit_message": None,
        "auto_devops_enabled": False,
        "auto_devops_deploy_strategy": "continuous",
        "autoclose_referenced_issues": True,
        "approvals_before_merge": 0,
        "mirror": False,
        "external_authorization_classification_label": "",
        "marked_for_deletion_at": None,
        "marked_for_deletion_on": None,
        "compliance_frameworks": [],
        "permissions": {"project_access": {"access_level": 40, "notification_level": 3}, "group_access": None},
    }


@pytest.fixture()
def gitlab_repository_languages_json() -> dict:
    return {"JavaScript": 84.89, "HTML": 7.07, "Dockerfile": 5.19, "CSS": 2.85}


@pytest.fixture()
def gitlab_repository_issues_json() -> list:
    return [
        {
            "id": 34359307,
            "iid": 3,
            "project_id": 18579664,
            "title": "Issue #3",
            "description": "bbasadsadasd",
            "state": "opened",
            "created_at": "2020-05-10T15:22:26.076Z",
            "updated_at": "2020-05-29T19:08:40.970Z",
            "closed_at": None,
            "closed_by": None,
            "labels": [],
            "milestone": None,
            "assignees": [],
            "author": {
                "id": 927868,
                "name": "stefanitsky",
                "username": "stefanitsky",
                "state": "active",
                "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
                "web_url": "https://gitlab.com/stefanitsky",
            },
            "assignee": None,
            "user_notes_count": 0,
            "merge_requests_count": 0,
            "upvotes": 0,
            "downvotes": 0,
            "due_date": None,
            "confidential": False,
            "discussion_locked": None,
            "web_url": "https://gitlab.com/stefanitsky/test2/-/issues/3",
            "time_stats": {
                "time_estimate": 0,
                "total_time_spent": 0,
                "human_time_estimate": None,
                "human_total_time_spent": None,
            },
            "task_completion_status": {"count": 0, "completed_count": 0},
            "weight": None,
            "blocking_issues_count": None,
            "has_tasks": False,
            "_links": {
                "self": "https://gitlab.com/api/v4/projects/18579664/issues/3",
                "notes": "https://gitlab.com/api/v4/projects/18579664/issues/3/notes",
                "award_emoji": "https://gitlab.com/api/v4/projects/18579664/issues/3/award_emoji",
                "project": "https://gitlab.com/api/v4/projects/18579664",
            },
            "references": {"short": "#3", "relative": "#3", "full": "stefanitsky/test2#3"},
            "moved_to_id": None,
        },
        {
            "id": 34358469,
            "iid": 2,
            "project_id": 18579664,
            "title": "New issue #2",
            "description": "123",
            "state": "closed",
            "created_at": "2020-05-10T14:21:13.791Z",
            "updated_at": "2020-05-10T15:21:49.097Z",
            "closed_at": "2020-05-10T15:21:49.083Z",
            "closed_by": {
                "id": 927868,
                "name": "stefanitsky",
                "username": "stefanitsky",
                "state": "active",
                "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
                "web_url": "https://gitlab.com/stefanitsky",
            },
            "labels": [],
            "milestone": None,
            "assignees": [],
            "author": {
                "id": 927868,
                "name": "stefanitsky",
                "username": "stefanitsky",
                "state": "active",
                "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
                "web_url": "https://gitlab.com/stefanitsky",
            },
            "assignee": None,
            "user_notes_count": 0,
            "merge_requests_count": 0,
            "upvotes": 0,
            "downvotes": 0,
            "due_date": None,
            "confidential": False,
            "discussion_locked": None,
            "web_url": "https://gitlab.com/stefanitsky/test2/-/issues/2",
            "time_stats": {
                "time_estimate": 0,
                "total_time_spent": 0,
                "human_time_estimate": None,
                "human_total_time_spent": None,
            },
            "task_completion_status": {"count": 0, "completed_count": 0},
            "weight": None,
            "blocking_issues_count": None,
            "has_tasks": False,
            "_links": {
                "self": "https://gitlab.com/api/v4/projects/18579664/issues/2",
                "notes": "https://gitlab.com/api/v4/projects/18579664/issues/2/notes",
                "award_emoji": "https://gitlab.com/api/v4/projects/18579664/issues/2/award_emoji",
                "project": "https://gitlab.com/api/v4/projects/18579664",
            },
            "references": {"short": "#2", "relative": "#2", "full": "stefanitsky/test2#2"},
            "moved_to_id": None,
        },
        {
            "id": 34132386,
            "iid": 1,
            "project_id": 18579664,
            "title": "Issue number one",
            "description": "Just issue, nothing special.",
            "state": "opened",
            "created_at": "2020-05-04T23:35:54.730Z",
            "updated_at": "2020-07-19T19:00:09.030Z",
            "closed_at": None,
            "closed_by": None,
            "labels": [],
            "milestone": None,
            "assignees": [],
            "author": {
                "id": 927868,
                "name": "stefanitsky",
                "username": "stefanitsky",
                "state": "active",
                "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
                "web_url": "https://gitlab.com/stefanitsky",
            },
            "assignee": None,
            "user_notes_count": 0,
            "merge_requests_count": 0,
            "upvotes": 0,
            "downvotes": 0,
            "due_date": None,
            "confidential": False,
            "discussion_locked": None,
            "web_url": "https://gitlab.com/stefanitsky/test2/-/issues/1",
            "time_stats": {
                "time_estimate": 0,
                "total_time_spent": 0,
                "human_time_estimate": None,
                "human_total_time_spent": None,
            },
            "task_completion_status": {"count": 0, "completed_count": 0},
            "weight": None,
            "blocking_issues_count": None,
            "has_tasks": False,
            "_links": {
                "self": "https://gitlab.com/api/v4/projects/18579664/issues/1",
                "notes": "https://gitlab.com/api/v4/projects/18579664/issues/1/notes",
                "award_emoji": "https://gitlab.com/api/v4/projects/18579664/issues/1/award_emoji",
                "project": "https://gitlab.com/api/v4/projects/18579664",
            },
            "references": {"short": "#1", "relative": "#1", "full": "stefanitsky/test2#1"},
            "moved_to_id": None,
        },
    ]


@pytest.fixture()
def gitlab_webhook_create_json() -> dict:
    return {
        "id": 4626222,
        "url": "https://openwiden.com/api/v1/webhooks/gitlab/1/receive/",
        "created_at": "2020-07-28T15:42:41.244Z",
        "push_events": True,
        "tag_push_events": False,
        "merge_requests_events": False,
        "repository_update_events": False,
        "enable_ssl_verification": True,
        "project_id": 18579664,
        "issues_events": True,
        "confidential_issues_events": False,
        "note_events": False,
        "confidential_note_events": None,
        "pipeline_events": False,
        "wiki_page_events": False,
        "job_events": False,
        "push_events_branch_filter": None,
    }
