EVENT_PAYLOAD = {
    "object_kind": "push",
    "event_name": "push",
    "before": "cca5d1d2fb24ad6e945aa56f2c848c76a2cc1c61",
    "after": "9c000c927308cdd4a1344b7720c014184a3209bf",
    "ref": "refs/heads/master",
    "checkout_sha": "9c000c927308cdd4a1344b7720c014184a3209bf",
    "message": None,
    "user_id": 927868,
    "user_name": "stefanitsky",
    "user_username": "stefanitsky",
    "user_email": "stefanitsky.mozdor@gmail.com",
    "user_avatar": "https://gitlab.com/uploads/-/system/user/avatar/927868/avatar.png",
    "project_id": 18579664,
    "project": {
        "id": 18579664,
        "name": "Test21",
        "description": "",
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "commits": [
        {
            "id": "9c000c927308cdd4a1344b7720c014184a3209bf",
            "message": "Update README.md",
            "title": "Update README.md",
            "timestamp": "2020-08-17T18:41:30+00:00",
            "url": "https://gitlab.com/stefanitsky/test2/-/commit/9c000c927308cdd4a1344b7720c014184a3209bf",
            "author": {"name": "stefanitsky", "email": "stefanitsky.mozdor@gmail.com"},
            "added": [],
            "modified": ["README.md"],
            "removed": [],
        }
    ],
    "total_commits_count": 1,
    "push_options": {},
    "repository": {
        "name": "Test21",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": "",
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "visibility_level": 20,
    },
}
