import pytest
from django.urls import reverse
from rest_framework import status

from gitlab_webhooks.constants import Events
from openwiden.enums import VersionControlService


OPEN_EVENT = {
    "object_kind": "issue",
    "event_type": "issue",
    "user": {
        "name": "stefanitsky",
        "username": "stefanitsky",
        "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
        "email": "stefanitsky.mozdor@gmail.com",
    },
    "project": {
        "id": 18579664,
        "name": "Test2",
        "description": None,
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "object_attributes": {
        "author_id": 927868,
        "closed_at": None,
        "confidential": False,
        "created_at": "2020-08-17 18:11:16 UTC",
        "description": "ASDAS",
        "discussion_locked": None,
        "due_date": None,
        "id": 69926405,
        "iid": 5,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "milestone_id": None,
        "moved_to_id": None,
        "duplicated_to_id": None,
        "project_id": 18579664,
        "relative_position": 1073744323,
        "state_id": 1,
        "time_estimate": 0,
        "title": "ADASDAS",
        "updated_at": "2020-08-17 18:11:16 UTC",
        "updated_by_id": None,
        "weight": None,
        "url": "https://gitlab.com/stefanitsky/test2/-/issues/5",
        "total_time_spent": 0,
        "human_total_time_spent": None,
        "human_time_estimate": None,
        "assignee_ids": [],
        "assignee_id": None,
        "labels": [],
        "state": "opened",
        "action": "open",
    },
    "labels": [],
    "changes": {
        "author_id": {"previous": None, "current": 927868},
        "created_at": {"previous": None, "current": "2020-08-17 18:11:16 UTC"},
        "description": {"previous": None, "current": "ASDAS"},
        "id": {"previous": None, "current": 69926405},
        "iid": {"previous": None, "current": 5},
        "project_id": {"previous": None, "current": 18579664},
        "relative_position": {"previous": None, "current": 1073744323},
        "title": {"previous": None, "current": "ADASDAS"},
        "updated_at": {"previous": None, "current": "2020-08-17 18:11:16 UTC"},
    },
    "repository": {
        "name": "Test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
    },
}


CLOSE_EVENT = {
    "object_kind": "issue",
    "event_type": "issue",
    "user": {
        "name": "stefanitsky",
        "username": "stefanitsky",
        "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
        "email": "stefanitsky.mozdor@gmail.com",
    },
    "project": {
        "id": 18579664,
        "name": "Test2",
        "description": None,
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "object_attributes": {
        "author_id": 927868,
        "closed_at": "2020-08-17 18:17:57 UTC",
        "confidential": False,
        "created_at": "2020-08-17 18:11:16 UTC",
        "description": "ASDAS",
        "discussion_locked": None,
        "due_date": None,
        "id": 69926405,
        "iid": 5,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "milestone_id": None,
        "moved_to_id": None,
        "duplicated_to_id": None,
        "project_id": 18579664,
        "relative_position": 1073744323,
        "state_id": 2,
        "time_estimate": 0,
        "title": "ADASDAS",
        "updated_at": "2020-08-17 18:17:57 UTC",
        "updated_by_id": None,
        "weight": None,
        "url": "https://gitlab.com/stefanitsky/test2/-/issues/5",
        "total_time_spent": 0,
        "human_total_time_spent": None,
        "human_time_estimate": None,
        "assignee_ids": [],
        "assignee_id": None,
        "labels": [],
        "state": "closed",
        "action": "close",
    },
    "labels": [],
    "changes": {"updated_at": {"previous": "2020-08-17 18:17:57 UTC", "current": "2020-08-17 18:17:57 UTC"}},
    "repository": {
        "name": "Test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
    },
}

REOPEN_EVENT = {
    "object_kind": "issue",
    "event_type": "issue",
    "user": {
        "name": "stefanitsky",
        "username": "stefanitsky",
        "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
        "email": "stefanitsky.mozdor@gmail.com",
    },
    "project": {
        "id": 18579664,
        "name": "Test2",
        "description": None,
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "object_attributes": {
        "author_id": 927868,
        "closed_at": None,
        "confidential": False,
        "created_at": "2020-08-17 18:11:16 UTC",
        "description": "ASDAS",
        "discussion_locked": None,
        "due_date": None,
        "id": 69926405,
        "iid": 5,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "milestone_id": None,
        "moved_to_id": None,
        "duplicated_to_id": None,
        "project_id": 18579664,
        "relative_position": 1073744323,
        "state_id": 1,
        "time_estimate": 0,
        "title": "ADASDAS",
        "updated_at": "2020-08-17 18:19:45 UTC",
        "updated_by_id": None,
        "weight": None,
        "url": "https://gitlab.com/stefanitsky/test2/-/issues/5",
        "total_time_spent": 0,
        "human_total_time_spent": None,
        "human_time_estimate": None,
        "assignee_ids": [],
        "assignee_id": None,
        "labels": [],
        "state": "opened",
        "action": "reopen",
    },
    "labels": [],
    "changes": {
        "closed_at": {"previous": "2020-08-17 18:17:57 UTC", "current": None},
        "state_id": {"previous": 2, "current": 1},
        "updated_at": {"previous": "2020-08-17 18:17:57 UTC", "current": "2020-08-17 18:19:45 UTC"},
    },
    "repository": {
        "name": "Test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
    },
}

UPDATE_EVENT = {
    "object_kind": "issue",
    "event_type": "issue",
    "user": {
        "name": "stefanitsky",
        "username": "stefanitsky",
        "avatar_url": "https://assets.gitlab-static.net/uploads/-/system/user/avatar/927868/avatar.png",
        "email": "stefanitsky.mozdor@gmail.com",
    },
    "project": {
        "id": 18579664,
        "name": "Test2",
        "description": None,
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "object_attributes": {
        "author_id": 927868,
        "closed_at": "2020-08-17 18:19:49 UTC",
        "confidential": False,
        "created_at": "2020-08-17 18:11:16 UTC",
        "description": "Description changed",
        "discussion_locked": None,
        "due_date": None,
        "id": 69926405,
        "iid": 5,
        "last_edited_at": "2020-08-17 18:20:08 UTC",
        "last_edited_by_id": 927868,
        "milestone_id": None,
        "moved_to_id": None,
        "duplicated_to_id": None,
        "project_id": 18579664,
        "relative_position": 1073744323,
        "state_id": 2,
        "time_estimate": 0,
        "title": "Name changed",
        "updated_at": "2020-08-17 18:20:08 UTC",
        "updated_by_id": 927868,
        "weight": None,
        "url": "https://gitlab.com/stefanitsky/test2/-/issues/5",
        "total_time_spent": 0,
        "human_total_time_spent": None,
        "human_time_estimate": None,
        "assignee_ids": [],
        "assignee_id": None,
        "labels": [],
        "state": "closed",
        "action": "update",
    },
    "labels": [],
    "changes": {
        "description": {"previous": "ASDAS", "current": "Description changed"},
        "last_edited_at": {"previous": None, "current": "2020-08-17 18:20:08 UTC"},
        "last_edited_by_id": {"previous": None, "current": 927868},
        "title": {"previous": "ADASDAS", "current": "Name changed"},
        "updated_at": {"previous": "2020-08-17 18:19:49 UTC", "current": "2020-08-17 18:20:08 UTC"},
        "updated_by_id": {"previous": None, "current": 927868},
    },
    "repository": {
        "name": "Test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
    },
}


@pytest.mark.django_db
@pytest.mark.functional
@pytest.mark.parametrize(
    "payload",
    [
        pytest.param(OPEN_EVENT, id="open event"),
        pytest.param(CLOSE_EVENT, id="close event"),
        pytest.param(REOPEN_EVENT, id="reopen event"),
        pytest.param(UPDATE_EVENT, id="update event"),
    ],
)
def test_run(
    create_repository, create_repo_webhook, create_api_client, payload: dict,
):
    # Crete api client and instances
    api_client = create_api_client()
    repository = create_repository(remote_id=payload["project"]["id"], vcs=VersionControlService.GITLAB,)
    repository_webhook = create_repo_webhook(repository=repository, secret="12345")

    # Make webhook request
    url = reverse("api-v1:webhooks:gitlab", kwargs={"id": str(repository_webhook.id)})
    headers = {
        "HTTP_X_GITLAB_TOKEN": repository_webhook.secret,
        "HTTP_X_GITLAB_EVENT": Events.ISSUE,
    }
    response = api_client.post(url, data=payload, format="json", **headers)

    # Test
    assert response.status_code == status.HTTP_200_OK
    assert repository.issues.filter(remote_id=payload["object_attributes"]["id"]).exists()
