OPEN_EVENT = {
    "object_kind": "tag_push",
    "event_name": "tag_push",
    "before": "0000000000000000000000000000000000000000",
    "after": "b77f250e6158df2f0d2ad9885a74ba6594651064",
    "ref": "refs/tags/Test11",
    "checkout_sha": "cca5d1d2fb24ad6e945aa56f2c848c76a2cc1c61",
    "message": "aaa",
    "user_id": 927868,
    "user_name": "stefanitsky",
    "user_username": "stefanitsky",
    "user_email": "stefanitsky.mozdor@gmail.com",
    "user_avatar": "https://gitlab.com/uploads/-/system/user/avatar/927868/avatar.png",
    "project_id": 18579664,
    "project": {
        "id": 18579664,
        "name": "Test21",
        "description": "",
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "commits": [
        {
            "id": "cca5d1d2fb24ad6e945aa56f2c848c76a2cc1c61",
            "message": "Initial template creation\n",
            "title": "Initial template creation",
            "timestamp": "2019-03-06T09:51:55+01:00",
            "url": "https://gitlab.com/stefanitsky/test2/-/commit/cca5d1d2fb24ad6e945aa56f2c848c76a2cc1c61",
            "author": {"name": "GitLab", "email": "root@localhost"},
            "added": [
                ".gitignore",
                ".node-version",
                "Dockerfile",
                "README.md",
                "app.js",
                "bin/www",
                "package-lock.json",
                "package.json",
                "public/stylesheets/style.css",
                "routes/index.js",
                "routes/users.js",
                "test/test.js",
                "views/error.pug",
                "views/index.pug",
                "views/layout.pug",
            ],
            "modified": [],
            "removed": [],
        }
    ],
    "total_commits_count": 1,
    "push_options": {},
    "repository": {
        "name": "Test21",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": "",
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "visibility_level": 20,
    },
}

DELETE_EVENT = {
    "object_kind": "tag_push",
    "event_name": "tag_push",
    "before": "b77f250e6158df2f0d2ad9885a74ba6594651064",
    "after": "0000000000000000000000000000000000000000",
    "ref": "refs/tags/Test11",
    "checkout_sha": None,
    "message": None,
    "user_id": 927868,
    "user_name": "stefanitsky",
    "user_username": "stefanitsky",
    "user_email": "stefanitsky.mozdor@gmail.com",
    "user_avatar": "https://gitlab.com/uploads/-/system/user/avatar/927868/avatar.png",
    "project_id": 18579664,
    "project": {
        "id": 18579664,
        "name": "Test21",
        "description": "",
        "web_url": "https://gitlab.com/stefanitsky/test2",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "namespace": "stefanitsky",
        "visibility_level": 20,
        "path_with_namespace": "stefanitsky/test2",
        "default_branch": "master",
        "ci_config_path": None,
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "http_url": "https://gitlab.com/stefanitsky/test2.git",
    },
    "commits": [],
    "total_commits_count": 0,
    "push_options": {},
    "repository": {
        "name": "Test21",
        "url": "git@gitlab.com:stefanitsky/test2.git",
        "description": "",
        "homepage": "https://gitlab.com/stefanitsky/test2",
        "git_http_url": "https://gitlab.com/stefanitsky/test2.git",
        "git_ssh_url": "git@gitlab.com:stefanitsky/test2.git",
        "visibility_level": 20,
    },
}
