# Generated by Django 3.0.5 on 2020-05-02 16:13

from django.conf import settings
from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_control_service', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'Gitlab')], max_length=50, verbose_name='version control service')),
                ('remote_id', models.PositiveIntegerField(verbose_name='remote id')),
                ('url', models.URLField(verbose_name='url')),
                ('avatar_url', models.URLField(verbose_name='avatar url')),
                ('description', models.CharField(max_length=255, verbose_name='the description of the company')),
                ('name', models.CharField(max_length=255, verbose_name='the shorthand name of the company')),
                ('company', models.CharField(max_length=255, verbose_name='company name')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('email', models.EmailField(max_length=254, verbose_name='publicity visible email')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('users', models.ManyToManyField(related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL, verbose_name='organization users')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'list of organizations',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('version_control_service', 'remote_id'), name='unique_organization'),
        ),
    ]
