# Generated by Django 3.0.5 on 2020-05-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vcs_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', related_query_name='org_membership', to='users.VCSAccount', verbose_name='version control service account'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('vcs_account', 'organization'), name='unique_member'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='member',
            order_with_respect_to='organization',
        ),
    ]
