# Generated by Django 3.0.5 on 2020-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200509_1417'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='version_control_service',
            new_name='vcs',
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('vcs', 'remote_id'), name='unique_org'),
        ),
    ]
