# Generated by Django 3.0.5 on 2020-05-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200502_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
