# Generated by Django 3.0.5 on 2020-05-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200502_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='the shorthand name of the company'),
            preserve_default=False,
        ),
    ]
