# Generated by Django 3.0.5 on 2020-05-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200502_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private'), ('internal', 'internal')], default='public', max_length=8, verbose_name='visibility'),
        ),
    ]
