# Generated by Django 3.0.5 on 2020-05-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
    ]
