# Generated by Django 3.0.5 on 2020-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20200504_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='has_webhook_permission',
        ),
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='has admin permissions'),
        ),
    ]
