# Generated by Django 3.0.5 on 2020-05-09 14:17

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryWebhook',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.PositiveIntegerField(verbose_name='remote id')),
                ('url', models.URLField(verbose_name='url')),
                ('secret', models.CharField(max_length=40, verbose_name='secret')),
                ('issue_events_enabled', models.BooleanField(verbose_name='issue events enabled')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repository', verbose_name='repository')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'list of webhooks',
            },
        ),
        migrations.AddConstraint(
            model_name='repositorywebhook',
            constraint=models.UniqueConstraint(fields=('repository', 'remote_id'), name='unique_repository_webhook'),
        ),
    ]
