# Generated by Django 3.0.5 on 2020-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_repositorywebhook_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorywebhook',
            name='issue_events_enabled',
            field=models.BooleanField(default=False, verbose_name='issue events enabled'),
        ),
    ]
