# Generated by Django 3.0.5 on 2020-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_auto_20200510_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorywebhook',
            name='remote_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='remote id'),
        ),
    ]
