# Generated by Django 3.0.5 on 2020-05-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20200510_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorywebhook',
            name='url',
        ),
    ]
