# Generated by Django 3.0.5 on 2020-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_remove_repositorywebhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorywebhook',
            name='url',
            field=models.URLField(default='', verbose_name='url'),
            preserve_default=False,
        ),
    ]
