# Generated by Django 3.0.5 on 2020-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_repositorywebhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorywebhook',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
