# Generated by Django 3.0.5 on 2020-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_remove_repository_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
