# Generated by Django 3.0.5 on 2020-05-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('repositories', '0003_auto_20200509_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', related_query_name='repository', to='users.VCSAccount', verbose_name='owner'),
        ),
    ]
