# Generated by Django 3.0.3 on 2020-04-26 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20200405_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='repository',
            name='programming_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='language'), default=[], size=None, verbose_name='programming languages'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
    ]
