# Generated by Django 3.0.5 on 2020-05-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_repository_is_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='is_removed',
        ),
    ]
