# Generated by Django 3.0.3 on 2020-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_auto_20200426_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='version_control_service',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'Gitlab')], max_length=50, verbose_name='version control service'),
        ),
        migrations.DeleteModel(
            name='VersionControlService',
        ),
    ]
