# Generated by Django 3.0.5 on 2020-05-02 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '0004_remove_repository_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', related_query_name='repository', to='organizations.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', related_query_name='repository', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
