# Generated by Django 3.0.5 on 2020-05-03 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20200502_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='programming_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='language'), blank=True, null=True, size=None, verbose_name='programming languages'),
        ),
    ]
