# Generated by Django 3.0.3 on 2020-05-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20200426_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_added',
            field=models.BooleanField(default=False, verbose_name='is added'),
        ),
    ]
