# Generated by Django 3.0.7 on 2020-08-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20200522_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='is_added',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='visibility',
        ),
        migrations.AddField(
            model_name='repository',
            name='state',
            field=models.CharField(choices=[('initial', 'initial'), ('adding', 'adding'), ('added', 'added'), ('removing', 'removing'), ('removed', 'removed'), ('add_failed', 'add failed')], default='initial', max_length=10, verbose_name='state'),
        ),
    ]
