# Generated by Django 3.0.7 on 2020-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_auto_20200809_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='state',
            field=models.CharField(choices=[('initial', 'initial'), ('adding', 'adding'), ('added', 'added'), ('removing', 'removing'), ('removed', 'removed'), ('add_failed', 'add failed'), ('remove_failed', 'remove failed')], default='initial', max_length=13, verbose_name='state'),
        ),
    ]
