# Generated by Django 3.0.5 on 2020-05-04 16:11
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_auto_20200503_1056'),
    ]

    operations = [
        HStoreExtension(),
    ]
