# Generated by Django 3.0.3 on 2020-05-01 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_repository_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='programming_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='language'), default=list, size=None, verbose_name='programming languages'),
        ),
    ]
