# Generated by Django 3.0.3 on 2020-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_auto_20200501_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('internal', 'internal')], default='private', max_length=8, verbose_name='visibility'),
            preserve_default=False,
        ),
    ]
