# Generated by Django 3.0.5 on 2020-05-04 16:13

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_auto_20200504_1611'),
    ]

    operations = [
        migrations.RemoveField('repository', 'programming_languages'),
        migrations.AddField(
            model_name='repository',
            name='programming_languages',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='programming languages'),
        ),
    ]
