# Generated by Django 3.0.5 on 2020-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0008_auto_20200504_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
