# Generated by Django 3.0.5 on 2020-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_auto_20200504_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='star_count',
        ),
        migrations.AddField(
            model_name='repository',
            name='stars_count',
            field=models.PositiveIntegerField(default=0, verbose_name='stars count'),
        ),
    ]
