# Generated by Django 3.0.5 on 2020-05-04 23:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0010_auto_20200504_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='labels'),
        ),
    ]
