# Generated by Django 3.0.2 on 2020-04-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ('name',), 'verbose_name': 'programming language', 'verbose_name_plural': 'list of programming languages'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ('-open_issues_count',), 'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
        migrations.AlterModelOptions(
            name='versioncontrolservice',
            options={'ordering': ('host',), 'verbose_name': 'version control service', 'verbose_name_plural': 'version control services'},
        ),
    ]
