# Generated by Django 3.0.2 on 2020-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20200309_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrolservice',
            name='label',
            field=models.CharField(max_length=30, unique=True, verbose_name='label'),
        ),
    ]
