# Generated by Django 3.0.2 on 2020-04-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20200405_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-created_at',), 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
    ]
