# Generated by Django 3.0.2 on 2020-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_auto_20200320_2147_squashed_0006_auto_20200320_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-open_issues_count'], 'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='closed at'),
        ),
    ]
