# Generated by Django 3.0.2 on 2020-03-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20200321_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
    ]
