# Generated by Django 3.0.2 on 2020-03-30 19:06
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_auto_20200322_1808'),
    ]

    operations = [
        HStoreExtension()
    ]
