# Generated by Django 3.0.2 on 2020-03-30 19:08

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_auto_20200330_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='programming_languages',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, verbose_name='repository languages'),
            preserve_default=False,
        ),
    ]
