from unittest import mock

import pytest
from django.urls import reverse
from rest_framework import status

from openwiden.enums import VersionControlService
from openwiden.repositories import models
from openwiden.webhooks.constants import IssueEventActions

DT_FORMAT = "%Y-%m-%dT%H:%M:%SZ"


OPENED_EVENT_PAYLOAD = {
    "action": "opened",
    "issue": {
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43",
        "repository_url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/labels{/name}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/comments",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/events",
        "html_url": "https://github.com/stefanitsky/yandex_market_language/issues/43",
        "id": 671143200,
        "node_id": "MDU6SXNzdWU2NzExNDMyMDA=",
        "number": 43,
        "title": "Test issue #2",
        "user": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [],
        "state": "open",
        "locked": False,
        "assignee": None,
        "assignees": [],
        "milestone": None,
        "comments": 0,
        "created_at": "2020-08-01T19:46:03Z",
        "updated_at": "2020-08-01T19:46:03Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": "Test issue description.",
        "performed_via_github_app": None
    },
    "repository": {
        "id": 250661059,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
        "name": "yandex_market_language",
        "full_name": "stefanitsky/yandex_market_language",
        "private": False,
        "owner": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "html_url": "https://github.com/stefanitsky/yandex_market_language",
        "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",  # noqa: E501
        "fork": False,
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
        "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",  # noqa: E501
        "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
        "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
        "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",  # noqa: E501
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
        "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
        "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
        "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
        "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
        "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
        "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
        "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
        "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
        "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",  # noqa: E501
        "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
        "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
        "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
        "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
        "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",  # noqa: E501
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
        "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
        "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
        "created_at": "2020-03-27T22:21:23Z",
        "updated_at": "2020-07-31T19:29:46Z",
        "pushed_at": "2020-07-31T19:29:44Z",
        "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
        "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
        "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
        "svn_url": "https://github.com/stefanitsky/yandex_market_language",
        "homepage": None,
        "size": 193,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 2,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 3,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": None,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 2,
        "open_issues": 3,
        "watchers": 3,
        "default_branch": "master"
    },
    "sender": {
        "login": "stefanitsky",
        "id": 22547214,
        "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
        "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stefanitsky",
        "html_url": "https://github.com/stefanitsky",
        "followers_url": "https://api.github.com/users/stefanitsky/followers",
        "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
        "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
        "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
        "repos_url": "https://api.github.com/users/stefanitsky/repos",
        "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
        "type": "User",
        "site_admin": False
    }
}

LABELED_EVENT_PAYLOAD = {
    "action": "labeled",
    "issue": {
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43",
        "repository_url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/labels{/name}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/comments",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/events",
        "html_url": "https://github.com/stefanitsky/yandex_market_language/issues/43",
        "id": 671143200,
        "node_id": "MDU6SXNzdWU2NzExNDMyMDA=",
        "number": 43,
        "title": "Test issue #2",
        "user": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [
            {
                "id": 1939951514,
                "node_id": "MDU6TGFiZWwxOTM5OTUxNTE0",
                "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels/bug",
                "name": "bug",
                "color": "d73a4a",
                "default": True,
                "description": "Something isn't working"
            }
        ],
        "state": "open",
        "locked": False,
        "assignee": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "assignees": [
            {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False
            }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2020-08-01T19:46:03Z",
        "updated_at": "2020-08-01T20:37:40Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": "Test issue description.",
        "performed_via_github_app": None
    },
    "label": {
        "id": 1939951514,
        "node_id": "MDU6TGFiZWwxOTM5OTUxNTE0",
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels/bug",
        "name": "bug",
        "color": "d73a4a",
        "default": True,
        "description": "Something isn't working"
    },
    "repository": {
        "id": 250661059,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
        "name": "yandex_market_language",
        "full_name": "stefanitsky/yandex_market_language",
        "private": False,
        "owner": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "html_url": "https://github.com/stefanitsky/yandex_market_language",
        "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",  # noqa: E501
        "fork": False,
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
        "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",  # noqa: E501
        "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
        "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
        "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",  # noqa: E501
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
        "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
        "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
        "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
        "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
        "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
        "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
        "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
        "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
        "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",  # noqa: E501
        "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
        "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
        "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
        "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
        "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",  # noqa: E501
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
        "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
        "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
        "created_at": "2020-03-27T22:21:23Z",
        "updated_at": "2020-07-31T19:29:46Z",
        "pushed_at": "2020-07-31T19:29:44Z",
        "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
        "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
        "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
        "svn_url": "https://github.com/stefanitsky/yandex_market_language",
        "homepage": None,
        "size": 193,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 2,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 3,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": None,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 2,
        "open_issues": 3,
        "watchers": 3,
        "default_branch": "master"
    },
    "sender": {
        "login": "stefanitsky",
        "id": 22547214,
        "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
        "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stefanitsky",
        "html_url": "https://github.com/stefanitsky",
        "followers_url": "https://api.github.com/users/stefanitsky/followers",
        "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
        "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
        "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
        "repos_url": "https://api.github.com/users/stefanitsky/repos",
        "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
        "type": "User",
        "site_admin": False
    }
}

UNLABELED_EVENT_PAYLOAD = {
    "action": "unlabeled",
    "issue": {
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43",
        "repository_url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/labels{/name}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/comments",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/events",
        "html_url": "https://github.com/stefanitsky/yandex_market_language/issues/43",
        "id": 671143200,
        "node_id": "MDU6SXNzdWU2NzExNDMyMDA=",
        "number": 43,
        "title": "Test issue #3",
        "user": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [],
        "state": "closed",
        "locked": False,
        "assignee": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "assignees": [
            {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False
            }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2020-08-01T19:46:03Z",
        "updated_at": "2020-08-01T21:12:45Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": "Test issue description.",
        "performed_via_github_app": None
    },
    "label": {
        "id": 1939951514,
        "node_id": "MDU6TGFiZWwxOTM5OTUxNTE0",
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels/bug",
        "name": "bug",
        "color": "d73a4a",
        "default": True,
        "description": "Something isn't working"
    },
    "repository": {
    "id": 250661059,
    "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
    "name": "yandex_market_language",
    "full_name": "stefanitsky/yandex_market_language",
    "private": False,
    "owner": {
      "login": "stefanitsky",
      "id": 22547214,
      "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanitsky",
      "html_url": "https://github.com/stefanitsky",
      "followers_url": "https://api.github.com/users/stefanitsky/followers",
      "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
      "repos_url": "https://api.github.com/users/stefanitsky/repos",
      "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
      "type": "User",
      "site_admin": False
    },
    "html_url": "https://github.com/stefanitsky/yandex_market_language",
    "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",
    "fork": False,
    "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
    "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
    "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
    "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
    "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",
    "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
    "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
    "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
    "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
    "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
    "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
    "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
    "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
    "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
    "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
    "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
    "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
    "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
    "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
    "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
    "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
    "created_at": "2020-03-27T22:21:23Z",
    "updated_at": "2020-07-31T19:29:46Z",
    "pushed_at": "2020-07-31T19:29:44Z",
    "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
    "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
    "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
    "svn_url": "https://github.com/stefanitsky/yandex_market_language",
    "homepage": None,
    "size": 193,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "Python",
    "has_issues": True,
    "has_projects": True,
    "has_downloads": True,
    "has_wiki": True,
    "has_pages": False,
    "forks_count": 2,
    "mirror_url": None,
    "archived": False,
    "disabled": False,
    "open_issues_count": 2,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": None,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "forks": 2,
    "open_issues": 2,
    "watchers": 3,
    "default_branch": "master"
  },
    "sender": {
    "login": "stefanitsky",
    "id": 22547214,
    "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
    "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/stefanitsky",
    "html_url": "https://github.com/stefanitsky",
    "followers_url": "https://api.github.com/users/stefanitsky/followers",
    "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
    "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
    "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
    "repos_url": "https://api.github.com/users/stefanitsky/repos",
    "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
    "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
    "type": "User",
    "site_admin": False
  }
}

CLOSED_EVENT_PAYLOAD = {
    "action": "closed",
    "issue": {
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43",
        "repository_url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/labels{/name}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/comments",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/events",
        "html_url": "https://github.com/stefanitsky/yandex_market_language/issues/43",
        "id": 671143200,
        "node_id": "MDU6SXNzdWU2NzExNDMyMDA=",
        "number": 43,
        "title": "Test issue #3",
        "user": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [
            {
                "id": 1939951514,
                "node_id": "MDU6TGFiZWwxOTM5OTUxNTE0",
                "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels/bug",
                "name": "bug",
                "color": "d73a4a",
                "default": True,
                "description": "Something isn't working"
            }
        ],
        "state": "closed",
        "locked": False,
        "assignee": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "assignees": [
            {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False
            }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2020-08-01T19:46:03Z",
        "updated_at": "2020-08-01T21:09:32Z",
        "closed_at": "2020-08-01T21:09:32Z",
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": "Test issue description.",
        "performed_via_github_app": None
    },
    "repository": {
        "id": 250661059,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
        "name": "yandex_market_language",
        "full_name": "stefanitsky/yandex_market_language",
        "private": False,
        "owner": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "html_url": "https://github.com/stefanitsky/yandex_market_language",
        "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",  # noqa: E501
        "fork": False,
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
        "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",  # noqa: E501
        "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
        "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
        "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
        "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
        "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
        "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
        "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
        "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
        "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
        "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
        "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
        "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
        "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
        "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
        "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
        "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",  # noqa: E501
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
        "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
        "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
        "created_at": "2020-03-27T22:21:23Z",
        "updated_at": "2020-07-31T19:29:46Z",
        "pushed_at": "2020-07-31T19:29:44Z",
        "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
        "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
        "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
        "svn_url": "https://github.com/stefanitsky/yandex_market_language",
        "homepage": None,
        "size": 193,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 2,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 2,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": None,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 2,
        "open_issues": 2,
        "watchers": 3,
        "default_branch": "master"
    },
    "sender": {
        "login": "stefanitsky",
        "id": 22547214,
        "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
        "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stefanitsky",
        "html_url": "https://github.com/stefanitsky",
        "followers_url": "https://api.github.com/users/stefanitsky/followers",
        "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
        "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
        "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
        "repos_url": "https://api.github.com/users/stefanitsky/repos",
        "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
        "type": "User",
        "site_admin": False
    }
}

EDITED_EVENT_PAYLOAD = {
    "action": "edited",
    "issue": {
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43",
        "repository_url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/labels{/name}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/comments",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/events",
        "html_url": "https://github.com/stefanitsky/yandex_market_language/issues/43",
        "id": 671143200,
        "node_id": "MDU6SXNzdWU2NzExNDMyMDA=",
        "number": 43,
        "title": "Test issue #3",
        "user": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [
            {
                "id": 1939951514,
                "node_id": "MDU6TGFiZWwxOTM5OTUxNTE0",
                "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels/bug",
                "name": "bug",
                "color": "d73a4a",
                "default": True,
                "description": "Something isn't working"
            }
        ],
        "state": "open",
        "locked": False,
        "assignee": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "assignees": [
            {
                "login": "stefanitsky",
                "id": 22547214,
                "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stefanitsky",
                "html_url": "https://github.com/stefanitsky",
                "followers_url": "https://api.github.com/users/stefanitsky/followers",
                "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
                "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
                "repos_url": "https://api.github.com/users/stefanitsky/repos",
                "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
                "type": "User",
                "site_admin": False
            }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2020-08-01T19:46:03Z",
        "updated_at": "2020-08-01T21:09:18Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": "Test issue description.",
        "performed_via_github_app": None
    },
    "changes": {
        "title": {
            "from": "Test issue #2"
        }
    },
    "repository": {
        "id": 250661059,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
        "name": "yandex_market_language",
        "full_name": "stefanitsky/yandex_market_language",
        "private": False,
        "owner": {
            "login": "stefanitsky",
            "id": 22547214,
            "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stefanitsky",
            "html_url": "https://github.com/stefanitsky",
            "followers_url": "https://api.github.com/users/stefanitsky/followers",
            "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
            "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
            "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
            "repos_url": "https://api.github.com/users/stefanitsky/repos",
            "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
            "type": "User",
            "site_admin": False
        },
        "html_url": "https://github.com/stefanitsky/yandex_market_language",
        "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",  # noqa: E501
        "fork": False,
        "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
        "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
        "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",  # noqa: E501
        "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
        "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
        "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",
        "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
        "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
        "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
        "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
        "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
        "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
        "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
        "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
        "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
        "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",  # noqa: E501
        "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
        "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
        "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
        "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
        "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",  # noqa: E501
        "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
        "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
        "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
        "created_at": "2020-03-27T22:21:23Z",
        "updated_at": "2020-07-31T19:29:46Z",
        "pushed_at": "2020-07-31T19:29:44Z",
        "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
        "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
        "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
        "svn_url": "https://github.com/stefanitsky/yandex_market_language",
        "homepage": None,
        "size": 193,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 2,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 3,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": None,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 2,
        "open_issues": 3,
        "watchers": 3,
        "default_branch": "master"
    },
    "sender": {
        "login": "stefanitsky",
        "id": 22547214,
        "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
        "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stefanitsky",
        "html_url": "https://github.com/stefanitsky",
        "followers_url": "https://api.github.com/users/stefanitsky/followers",
        "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
        "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
        "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
        "repos_url": "https://api.github.com/users/stefanitsky/repos",
        "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
        "type": "User",
        "site_admin": False
    }
}

DELETE_EVENT_PAYLOAD = {
  "action": "deleted",
  "issue": {
    "url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43",
    "repository_url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
    "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/labels{/name}",
    "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/comments",
    "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/43/events",
    "html_url": "https://github.com/stefanitsky/yandex_market_language/issues/43",
    "id": 671143200,
    "node_id": "MDU6SXNzdWU2NzExNDMyMDA=",
    "number": 43,
    "title": "Test issue #3",
    "user": {
      "login": "stefanitsky",
      "id": 22547214,
      "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanitsky",
      "html_url": "https://github.com/stefanitsky",
      "followers_url": "https://api.github.com/users/stefanitsky/followers",
      "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
      "repos_url": "https://api.github.com/users/stefanitsky/repos",
      "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [

    ],
    "state": "closed",
    "locked": False,
    "assignee": {
      "login": "stefanitsky",
      "id": 22547214,
      "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanitsky",
      "html_url": "https://github.com/stefanitsky",
      "followers_url": "https://api.github.com/users/stefanitsky/followers",
      "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
      "repos_url": "https://api.github.com/users/stefanitsky/repos",
      "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
      "type": "User",
      "site_admin": False
    },
    "assignees": [
      {
        "login": "stefanitsky",
        "id": 22547214,
        "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
        "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stefanitsky",
        "html_url": "https://github.com/stefanitsky",
        "followers_url": "https://api.github.com/users/stefanitsky/followers",
        "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
        "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
        "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
        "repos_url": "https://api.github.com/users/stefanitsky/repos",
        "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
        "type": "User",
        "site_admin": False
      }
    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2020-08-01T19:46:03Z",
    "updated_at": "2020-08-01T21:12:45Z",
    "closed_at": "2020-08-01T21:09:32Z",
    "author_association": "OWNER",
    "active_lock_reason": None,
    "body": "Test issue description.",
    "performed_via_github_app": None
  },
  "repository": {
    "id": 250661059,
    "node_id": "MDEwOlJlcG9zaXRvcnkyNTA2NjEwNTk=",
    "name": "yandex_market_language",
    "full_name": "stefanitsky/yandex_market_language",
    "private": False,
    "owner": {
      "login": "stefanitsky",
      "id": 22547214,
      "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanitsky",
      "html_url": "https://github.com/stefanitsky",
      "followers_url": "https://api.github.com/users/stefanitsky/followers",
      "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
      "repos_url": "https://api.github.com/users/stefanitsky/repos",
      "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
      "type": "User",
      "site_admin": False
    },
    "html_url": "https://github.com/stefanitsky/yandex_market_language",
    "description": "Yandex Market Language for Python provides user-friendly interface for parsing or creating XML files.",
    "fork": False,
    "url": "https://api.github.com/repos/stefanitsky/yandex_market_language",
    "forks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/forks",
    "keys_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/teams",
    "hooks_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/hooks",
    "issue_events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/events{/number}",
    "events_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/events",
    "assignees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/assignees{/user}",
    "branches_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/branches{/branch}",
    "tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/tags",
    "blobs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/languages",
    "stargazers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/stargazers",
    "contributors_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contributors",
    "subscribers_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscribers",
    "subscription_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/subscription",
    "commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/contents/{+path}",
    "compare_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/merges",
    "archive_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/downloads",
    "issues_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/issues{/number}",
    "pulls_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/labels{/name}",
    "releases_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/releases{/id}",
    "deployments_url": "https://api.github.com/repos/stefanitsky/yandex_market_language/deployments",
    "created_at": "2020-03-27T22:21:23Z",
    "updated_at": "2020-07-31T19:29:46Z",
    "pushed_at": "2020-07-31T19:29:44Z",
    "git_url": "git://github.com/stefanitsky/yandex_market_language.git",
    "ssh_url": "git@github.com:stefanitsky/yandex_market_language.git",
    "clone_url": "https://github.com/stefanitsky/yandex_market_language.git",
    "svn_url": "https://github.com/stefanitsky/yandex_market_language",
    "homepage": None,
    "size": 193,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "Python",
    "has_issues": True,
    "has_projects": True,
    "has_downloads": True,
    "has_wiki": True,
    "has_pages": False,
    "forks_count": 2,
    "mirror_url": None,
    "archived": False,
    "disabled": False,
    "open_issues_count": 2,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": None,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "forks": 2,
    "open_issues": 2,
    "watchers": 3,
    "default_branch": "master"
  },
  "sender": {
    "login": "stefanitsky",
    "id": 22547214,
    "node_id": "MDQ6VXNlcjIyNTQ3MjE0",
    "avatar_url": "https://avatars3.githubusercontent.com/u/22547214?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/stefanitsky",
    "html_url": "https://github.com/stefanitsky",
    "followers_url": "https://api.github.com/users/stefanitsky/followers",
    "following_url": "https://api.github.com/users/stefanitsky/following{/other_user}",
    "gists_url": "https://api.github.com/users/stefanitsky/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/stefanitsky/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/stefanitsky/subscriptions",
    "organizations_url": "https://api.github.com/users/stefanitsky/orgs",
    "repos_url": "https://api.github.com/users/stefanitsky/repos",
    "events_url": "https://api.github.com/users/stefanitsky/events{/privacy}",
    "received_events_url": "https://api.github.com/users/stefanitsky/received_events",
    "type": "User",
    "site_admin": False
  }
}


@pytest.mark.functional
@pytest.mark.django_db
@mock.patch("github_webhooks.utils.compare_signatures")
@pytest.mark.parametrize("payload, event", [
    pytest.param(OPENED_EVENT_PAYLOAD, IssueEventActions.OPENED, id="opened"),
    pytest.param(EDITED_EVENT_PAYLOAD, IssueEventActions.EDITED, id="edited"),
    pytest.param(CLOSED_EVENT_PAYLOAD, IssueEventActions.CLOSED, id="closed"),
    pytest.param(LABELED_EVENT_PAYLOAD, IssueEventActions.LABELED, id="labeled"),
    pytest.param(UNLABELED_EVENT_PAYLOAD, IssueEventActions.UNLABELED, id="unlabeled"),
    pytest.param(DELETE_EVENT_PAYLOAD, IssueEventActions.DELETED, id="deleted"),
])
def test_run(
    mock_compare_signatures,
    create_repository,
    create_repo_webhook,
    create_api_client,
    payload: dict,
    event: str,
):
    mock_compare_signatures.return_value = True
    api_client = create_api_client()
    repository = create_repository(
        vcs=VersionControlService.GITHUB,
        remote_id=payload["repository"]["id"],
    )
    repository_webhook = create_repo_webhook(repository=repository, secret=12345)
    issue_data = payload["issue"]

    # Make webhook event request
    url = reverse("v1:webhooks:github", kwargs={"id": str(repository_webhook.id)})
    response = api_client.post(
        url,
        data=payload,
        format="json",
        # Headers
        **{
            "HTTP_X_GITHUB_EVENT": "issues",
            "HTTP_X_HUB_SIGNATURE": "sha1=12345",
        },
    )

    # Test
    assert response.status_code == status.HTTP_200_OK
    if event in [
        IssueEventActions.OPENED,
        IssueEventActions.CLOSED,
        IssueEventActions.EDITED,
        IssueEventActions.LABELED,
        IssueEventActions.UNLABELED,
    ]:
        issue = models.Issue.objects.get(remote_id=issue_data["id"])
        assert issue.title == issue_data["title"]
        assert issue.description == issue_data["body"]
        assert issue.state == issue_data["state"]
        assert issue.labels == [label["name"] for label in issue_data["labels"]]
        assert issue.url == issue_data["html_url"]
        assert issue.created_at.strftime(DT_FORMAT) == issue_data["created_at"]
        assert issue.updated_at.strftime(DT_FORMAT) == issue_data["updated_at"]
        if event == IssueEventActions.CLOSED:
            assert issue.closed_at.strftime(DT_FORMAT) == issue_data["closed_at"]
        else:
            assert issue.closed_at == issue_data["closed_at"]
    elif event == IssueEventActions.DELETED:
        assert not models.Issue.objects.filter(remote_id=issue_data["id"]).exists()
